[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/r/:code"
  to = "/.netlify/functions/redirect?code=:code"
  status = 200
  force = true

[[redirects]]
  from = "/api/create"
  to = "/.netlify/functions/create"
  status = 200
  force = true

[[redirects]]
  from = "/api/update"
  to = "/.netlify/functions/update"
  status = 200
  force = true

[[redirects]]
  from = "/api/lookup"
  to = "/.netlify/functions/lookup"
  status = 200
  force = true
